package odms.commons.model._enum;

/**
 * Enum constructor for country codes
 */
public enum CountryCode {
    AD("Andorra"),
    AE("United Arab Emirates"),
    AF("Afghanistan"),
    AG("Antigua and Barbud"),
    AI("Anguilla"),
    AL("Albania"),
    AM("Armenia"),
    AN("Netherlands Antilles"),
    AO("Angola"),
    AQ("Antarctica"),
    AR("Argentina"),
    AS("American Samoa"),
    AT("Austria"),
    AU("Australia"),
    AW("Aruba"),
    AX("Aland Islands"),
    AZ("Azerbaijan"),
    BA("Bosnia and Herzegovina"),
    BB("Barbados"),
    BD("Bangladesh"),
    BE("Belgium"),
    BF("Burkina Faso"),
    BG("Bulgaria"),
    BH("Bahrain"),
    BI("Burundi"),
    BJ("Benin"),
    BL("Saint-Barthelemy"),
    BM("Bermuda"),
    BN("Brunei Darussalam"),
    BO("Bolivia"),
    BR("Brazil"),
    BS("Bahamas"),
    BT("Bhutan"),
    BV("Bouvet Island"),
    BW("Botswana"),
    BY("Belarus"),
    BZ("Belize"),
    CA("Canada"),
    CC("Cocos (Keeling) Islands"),
    CD("Congo, (Kinshasa)"),
    CF("Central African Republic"),
    CG("Congo (Brazzaville)"),
    CH("Switzerland"),
    CI("Cote D'Ivoire (Ivory Coast)"),
    CK("Cook Islands"),
    CL("Chile"),
    CM("Cameroon"),
    CN("China"),
    CO("Colombia"),
    CR("Costa Rica"),
    CU("Cuba"),
    CV("Cape Verde"),
    CX("Christmas Island"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DE("Germany"),
    DJ("Djibouti"),
    DK("Denmark"),
    DM("Dominica"),
    DO("Dominican Republic"),
    DZ("Algeria"),
    EE("Estonia"),
    EG("Egypt"),
    EH("Western Sahara"),
    ER("Eritrea"),
    ES("Spain"),
    ET("Ethiopia"),
    FI("Finland"),
    FJ("Fiji"),
    FK("Falkland Islands (Malvinas)"),
    FM("Micronesia, Federated States of"),
    FO("Faroe Islands"),
    FR("France"),
    GA("Gabon"),
    GB("United Kingdom (Great Britain)"),
    GD("Grenada"),
    GE("Georgia"),
    GF("French Guiana"),
    GG("Guernsey"),
    GH("Ghana"),
    GI("Gibraltar"),
    GL("Greenland"),
    GM("Gambia"),
    GN("Guinea"),
    GP("Guadeloupe"),
    GQ("Equatorial Guinea"),
    GR("Greece"),
    GS("South Georgia and South Sandwich Islands"),
    GT("Guatemala"),
    GU("Guam"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HK("Hong Kong, Special Admin Region of China"),
    HM("Heard and McDonald Islands"),
    HN("Honduras"),
    HR("Croatia"),
    HT("Haiti"),
    HU("Hungary"),
    ID("Indonesia"),
    IE("Ireland"),
    IL("Israel"),
    IM("Isle of Man"),
    IN("India"),
    IO("British Indian Ocean Territory"),
    IQ("Iraq"),
    IR("Iran, Islamic Republic of"),
    IS("Iceland"),
    IT("Italy"),
    JE("Jersey"),
    JM("Jamaica"),
    JO("Jordan"),
    JP("Japan"),
    KE("Kenya"),
    KG("Kyrgyzstan"),
    KH("Cambodia"),
    KI("Kiribati"),
    KM("Comoros"),
    KN("Saint Kitts and Nevis"),
    KP("Korea (North)"),
    KR("Korea (South)"),
    KW("Kuwait"),
    KY("Cayman Islands"),
    KZ("Kazakhstan"),
    LA("Lao, People's Democratic Republic"),
    LB("Lebanon"),
    LC("Saint Lucia"),
    LI("Liechtenstein"),
    LK("Sri Lanka"),
    LR("Liberia"),
    LS("Lesotho"),
    LT("Lithuania"),
    LU("Luxembourg"),
    LV("Latvia"),
    LY("Libya"),
    MA("Morocco"),
    MC("Monaco"),
    MD("Moldova"),
    ME("Montenegro"),
    MF("Saint-Martin (French Part)"),
    MG("Madagascar"),
    MH("Marshall Islands"),
    MK("Macedonia, the Former Yugoslav Republic of"),
    ML("Mali"),
    MM("Myanmar"),
    MN("Mongolia"),
    MO("Macao, Special Administrative Region of China"),
    MP("Northern Mariana Islands"),
    MQ("Martinique"),
    MR("Mauritania"),
    MS("Montserrat"),
    MT("Malta"),
    MU(""),
    MV(""),
    MW(""),
    MX(""),
    MY(""),
    MZ(""),
    NA(""),
    NC(""),
    NE(""),
    NF(""),
    NG(""),
    NI(""),
    NL(""),
    NO(""),
    NP(""),
    NR(""),
    NU(""),
    NZ(""),
    OM(""),
    PA(""),
    PE(""),
    PF(""),
    PG(""),
    PH(""),
    PK(""),
    PL(""),
    PM(""),
    PN(""),
    PR(""),
    PS(""),
    PT(""),
    PW(""),
    PY(""),
    QA(""),
    RE(""),
    RO(""),
    RS(""),
    RU(""),
    RW(""),
    SA(""),
    SB(""),
    SC(""),
    SD(""),
    SE(""),
    SG(""),
    SH(""),
    SI(""),
    SJ(""),
    SK(""),
    SL(""),
    SM(""),
    SN(""),
    SO(""),
    SR(""),
    SS(""),
    ST(""),
    SU(""),
    SV(""),
    SX(""),
    SY(""),
    SZ(""),
    TC(""),
    TD(""),
    TF(""),
    TG(""),
    TH(""),
    TJ(""),
    TK(""),
    TL(""),
    TM(""),
    TN(""),
    TO(""),
    TR(""),
    TT(""),
    TV(""),
    TW(""),
    TZ(""),
    UA(""),
    UG(""),
    UM(""),
    US(""),
    UY(""),
    UZ(""),
    VA(""),
    VC(""),
    VE(""),
    VG(""),
    VI(""),
    VN(""),
    VU(""),
    WF(""),
    WS(""),
    YE(""),
    YT(""),
    ZA(""),
    ZM(""),
    ZW("");


    private final String name;

    CountryCode(String s) {
        name = s;
    }

    public boolean equalsName(String otherName) {
        return name.equals(otherName);
    }

    @Override
    public String toString() {
        return this.name;
    }
}
